// web/src/pages/NotFound/index.tsx
import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/button'

export default function NotFound() {
  return (
    <div className="min-h-[60vh] flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-6xl font-bold text-gray-200">404</h1>
        <h2 className="mt-4 text-xl font-semibold text-gray-900">页面未找到</h2>
        <p className="mt-2 text-gray-500">您访问的页面不存在或已被移除</p>
        <div className="mt-6">
          <Button asChild>
            <Link to="/">返回首页</Link>
          </Button>
        </div>
      </div>
    </div>
  )
}

// web/src/pages/NotFound/index.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50">
    <div class="max-w-md w-full text-center">
      <div class="mb-8">
        <h1 class="text-9xl font-bold text-gray-300">404</h1>
        <h2 class="text-2xl font-semibold text-gray-900 mb-4">页面未找到</h2>
        <p class="text-gray-600 mb-8">
          抱歉，您访问的页面不存在或已被移除。
        </p>
      </div>

      <div class="space-y-4">
        <router-link
          to="/dashboard"
          class="btn btn-primary w-full"
        >
          返回首页
        </router-link>

        <button
          @click="$router.go(-1)"
          class="btn btn-secondary w-full"
        >
          返回上一页
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
// 404页面不需要额外逻辑
</script>
