// web/src/pages/ForgotPassword/index.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <div>
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
          重置密码
        </h2>
        <p class="mt-2 text-center text-sm text-gray-600">
          输入您的邮箱地址和验证码，设置新密码
        </p>
      </div>

      <!-- 错误提示 -->
      <div v-if="error" class="bg-red-50 border border-red-200 rounded-md p-4">
        <div class="flex">
          <div class="flex-shrink-0">
            <ExclamationCircleIcon class="h-5 w-5 text-red-400" />
          </div>
          <div class="ml-3">
            <p class="text-red-800">{{ error }}</p>
          </div>
        </div>
      </div>

      <!-- 成功提示 -->
      <div v-if="successMessage" class="bg-green-50 border border-green-200 rounded-md p-4">
        <div class="flex">
          <div class="flex-shrink-0">
            <CheckCircleIcon class="h-5 w-5 text-green-400" />
          </div>
          <div class="ml-3">
            <p class="text-green-800">{{ successMessage }}</p>
          </div>
        </div>
      </div>

      <form class="mt-8 space-y-6" @submit.prevent="handleSubmit">
        <div class="space-y-4">
          <div>
            <label for="email" class="block text-sm font-medium text-gray-700">邮箱地址</label>
            <input
              id="email"
              v-model="form.email"
              type="email"
              required
              :disabled="loading"
              class="mt-1 appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm disabled:opacity-50 disabled:cursor-not-allowed"
              placeholder="请输入您的邮箱"
            />
          </div>

          <div>
            <label for="code" class="block text-sm font-medium text-gray-700">验证码</label>
            <div class="mt-1 flex space-x-2">
              <input
                id="code"
                v-model="form.code"
                type="text"
                required
                :disabled="loading"
                class="flex-1 appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm disabled:opacity-50 disabled:cursor-not-allowed"
                placeholder="请输入验证码"
              />
              <button
                type="button"
                :disabled="sendCodeLoading || countdown > 0 || !isEmailValid"
                @click="handleSendCode"
                class="px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <span v-if="sendCodeLoading">发送中...</span>
                <span v-else-if="countdown > 0">{{ countdown }}s</span>
                <span v-else>发送验证码</span>
              </button>
            </div>
          </div>

          <div>
            <label for="newPassword" class="block text-sm font-medium text-gray-700">新密码</label>
            <input
              id="newPassword"
              v-model="form.newPassword"
              type="password"
              required
              :disabled="loading"
              class="mt-1 appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm disabled:opacity-50 disabled:cursor-not-allowed"
              placeholder="请输入新密码"
            />
          </div>

          <div>
            <label for="confirmPassword" class="block text-sm font-medium text-gray-700">确认新密码</label>
            <input
              id="confirmPassword"
              v-model="form.confirmPassword"
              type="password"
              required
              :disabled="loading"
              class="mt-1 appearance-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-md focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm disabled:opacity-50 disabled:cursor-not-allowed"
              placeholder="请再次输入新密码"
            />
          </div>
        </div>

        <div>
          <button
            type="submit"
            :disabled="loading || !isFormValid"
            class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            <span v-if="loading" class="absolute left-0 inset-y-0 flex items-center pl-3">
              <!-- Loading spinner -->
              <svg class="animate-spin h-5 w-5 text-blue-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
            </span>
            {{ loading ? '重置中...' : '重置密码' }}
          </button>
        </div>

        <div class="text-center">
          <router-link to="/login" class="font-medium text-blue-600 hover:text-blue-500">
            返回登录
          </router-link>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onBeforeUnmount } from 'vue'
import { useRouter } from 'vue-router'
import { ExclamationCircleIcon, CheckCircleIcon } from '@heroicons/vue/24/outline'
import { useAuth } from '@/hooks/user/useAuth'
import { useMessage } from '@/composables/useMessage'
import type { ResetPasswordRequest } from '@/types'

const router = useRouter()
const { resetPassword, sendResetPasswordCode, loading } = useAuth()
const { success, error: showError } = useMessage()

// 表单数据
const form = ref({
  email: '',
  code: '',
  newPassword: '',
  confirmPassword: ''
})

// 状态
const error = ref('')
const successMessage = ref('')
const sendCodeLoading = ref(false)
const countdown = ref(0)
let countdownTimer: NodeJS.Timeout | null = null

// 表单验证
const isEmailValid = computed(() => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  return emailRegex.test(form.value.email)
})

const isFormValid = computed(() => {
  return (
    form.value.email.trim() !== '' &&
    form.value.code.trim() !== '' &&
    form.value.newPassword.trim() !== '' &&
    form.value.confirmPassword.trim() !== '' &&
    form.value.newPassword === form.value.confirmPassword &&
    isEmailValid.value
  )
})

// 发送验证码
const handleSendCode = async () => {
  try {
    error.value = ''

    if (!form.value.email.trim()) {
      error.value = '请输入邮箱地址'
      return
    }

    if (!isEmailValid.value) {
      error.value = '请输入有效的邮箱地址'
      return
    }

    sendCodeLoading.value = true
    await sendResetPasswordCode(form.value.email.trim())

    success('验证码已发送到您的邮箱')

    // 开始倒计时
    startCountdown()

  } catch (err: unknown) {
    const errorMessage = err instanceof Error ? err.message : '发送验证码失败'
    error.value = errorMessage
    showError(errorMessage)
  } finally {
    sendCodeLoading.value = false
  }
}

// 开始倒计时
const startCountdown = () => {
  countdown.value = 60
  countdownTimer = setInterval(() => {
    countdown.value--
    if (countdown.value <= 0) {
      clearInterval(countdownTimer!)
      countdownTimer = null
    }
  }, 1000)
}

// 处理重置密码提交
const handleSubmit = async () => {
  try {
    error.value = ''
    successMessage.value = ''

    // 表单验证
    if (!form.value.email.trim()) {
      error.value = '请输入邮箱地址'
      return
    }

    if (!isEmailValid.value) {
      error.value = '请输入有效的邮箱地址'
      return
    }

    if (!form.value.code.trim()) {
      error.value = '请输入验证码'
      return
    }

    if (!form.value.newPassword.trim()) {
      error.value = '请输入新密码'
      return
    }

    if (form.value.newPassword.length < 6) {
      error.value = '密码长度不能少于6位'
      return
    }

    if (form.value.newPassword !== form.value.confirmPassword) {
      error.value = '两次输入的密码不一致'
      return
    }

    // 构造重置密码请求数据
    const resetData: ResetPasswordRequest = {
      email: form.value.email.trim(),
      code: form.value.code.trim(),
      newPassword: form.value.newPassword.trim()
    }

    // 调用重置密码API
    await resetPassword(resetData)

    // 重置成功
    successMessage.value = '密码重置成功！请使用新密码登录'
    success('密码重置成功！')

    // 延迟跳转到登录页
    setTimeout(() => {
      router.push('/login')
    }, 2000)

  } catch (err: unknown) {
    // 处理重置密码错误
    const errorMessage = err instanceof Error ? err.message : '重置密码失败，请重试'
    error.value = errorMessage
    showError(errorMessage)
  }
}

// 清理函数
onBeforeUnmount(() => {
  if (countdownTimer) {
    clearInterval(countdownTimer)
  }
})
</script>

// web/src/auth/pages/ForgotPassword.tsx
import { useState, useRef, useEffect } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../useAuth'
import { message } from '@/lib/message'
import type { ResetPasswordRequest } from '@/types/auth'

export default function ForgotPassword() {
  const navigate = useNavigate()
  const { resetPassword, sendResetPasswordCode, loading } = useAuth()

  const [form, setForm] = useState({
    email: '',
    code: '',
    newPassword: '',
    confirmPassword: '',
  })
  const [showPwd, setShowPwd] = useState(false)
  const [error, setError] = useState('')
  const [countdown, setCountdown] = useState(0)
  const timerRef = useRef<ReturnType<typeof setInterval>>(undefined)

  useEffect(
    () => () => {
      if (timerRef.current) clearInterval(timerRef.current)
    },
    [],
  )

  const canSubmit =
    form.email.trim().length > 0 &&
    form.code.trim().length > 0 &&
    form.newPassword.length >= 6 &&
    form.confirmPassword.length > 0

  const handleSendCode = async () => {
    if (!form.email.trim()) {
      setError('请输入邮箱')
      return
    }
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim())) {
      setError('请输入有效的邮箱地址')
      return
    }
    try {
      setError('')
      await sendResetPasswordCode(form.email.trim())
      message.success('验证码已发送到您的邮箱')
      setCountdown(60)
      timerRef.current = setInterval(() => {
        setCountdown((prev) => {
          if (prev <= 1) {
            clearInterval(timerRef.current)
            return 0
          }
          return prev - 1
        })
      }, 1000)
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : '发送验证码失败')
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    if (form.newPassword.length < 6 || form.newPassword.length > 20) {
      setError('密码长度为 6-20 个字符')
      return
    }
    if (form.newPassword !== form.confirmPassword) {
      setError('两次输入的密码不一致')
      return
    }
    try {
      const data: ResetPasswordRequest = {
        email: form.email.trim(),
        code: form.code.trim(),
        newPassword: form.newPassword,
      }
      await resetPassword(data)
      message.success('密码重置成功，请登录')
      setTimeout(() => navigate('/login'), 800)
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : '重置密码失败，请重试')
    }
  }

  const inputCls =
    'block w-full rounded-lg border border-gray-200 px-3.5 py-2.5 text-sm text-gray-900 placeholder:text-gray-400 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 outline-none transition disabled:bg-gray-50 disabled:opacity-60'

  return (
    <div className="min-h-screen flex">
      {/* Left dark panel */}
      <div
        className="hidden lg:flex lg:w-[45%] relative overflow-hidden items-center justify-center"
        style={{ background: 'linear-gradient(to bottom right, #0f172a, #1e293b)' }}
      >
        <div className="absolute top-1/4 left-1/4 w-72 h-72 rounded-full border border-white/[0.04]" />
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 rounded-full border border-white/[0.03]" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] rounded-full border border-white/[0.02]" />

        <div className="relative z-10 px-12 xl:px-20 max-w-lg">
          <div className="flex items-center gap-3 mb-16">
            <div
              className="w-10 h-10 rounded-xl flex items-center justify-center"
              style={{ background: 'linear-gradient(135deg, #3b82f6, #6366f1)' }}
            >
              <svg
                width="20"
                height="20"
                viewBox="0 0 24 24"
                fill="none"
                stroke="white"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M12 2L2 7l10 5 10-5-10-5z" />
                <path d="M2 17l10 5 10-5" />
                <path d="M2 12l10 5 10-5" />
              </svg>
            </div>
            <span
              className="text-white text-xl"
              style={{ fontFamily: "'Outfit', sans-serif", fontWeight: 700 }}
            >
              Gin Template
            </span>
          </div>

          <h1 className="text-4xl font-bold text-white leading-tight tracking-tight">重置密码</h1>
          <p className="mt-4 text-slate-400 text-base leading-relaxed">
            通过邮箱验证码安全地重置您的密码，整个过程只需几步。
          </p>

          <div className="mt-14 space-y-0">
            {[
              { step: '01', t: '输入注册邮箱', d: '我们将发送验证码到您的邮箱' },
              { step: '02', t: '填写验证码', d: '输入邮箱中收到的 6 位数字验证码' },
              { step: '03', t: '设置新密码', d: '输入并确认您的新密码即可完成' },
            ].map((item, i) => (
              <div key={item.step} className="flex items-start gap-4">
                <div className="relative flex flex-col items-center">
                  <div className="w-10 h-10 rounded-lg bg-blue-500/10 border border-blue-500/20 flex items-center justify-center shrink-0">
                    <span className="text-xs font-bold text-blue-400">{item.step}</span>
                  </div>
                  {i < 2 && <div className="w-px h-8 bg-white/10 mt-1" />}
                </div>
                <div className="pt-2">
                  <div className="text-sm font-medium text-white">{item.t}</div>
                  <div className="text-xs text-slate-500 mt-0.5">{item.d}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Right form panel */}
      <div className="flex-1 flex items-center justify-center px-6 sm:px-12 py-12 bg-white">
        <div className="w-full max-w-sm">
          <div className="lg:hidden flex items-center gap-2.5 mb-12">
            <div
              className="w-9 h-9 rounded-lg flex items-center justify-center"
              style={{ background: 'linear-gradient(135deg, #3b82f6, #6366f1)' }}
            >
              <svg
                width="18"
                height="18"
                viewBox="0 0 24 24"
                fill="none"
                stroke="white"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M12 2L2 7l10 5 10-5-10-5z" />
                <path d="M2 17l10 5 10-5" />
                <path d="M2 12l10 5 10-5" />
              </svg>
            </div>
            <span
              className="text-lg text-gray-900"
              style={{ fontFamily: "'Outfit', sans-serif", fontWeight: 700 }}
            >
              Gin Template
            </span>
          </div>

          <h2 className="text-2xl font-bold text-gray-900 tracking-tight">重置密码</h2>
          <p className="text-gray-500 text-sm mt-1.5 mb-7">通过邮箱验证码重置您的密码</p>

          {error && (
            <div className="mb-5 px-4 py-3 rounded-lg bg-red-50 border border-red-200 text-sm text-red-600 flex items-center gap-2">
              <svg
                width="16"
                height="16"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <circle cx="12" cy="12" r="10" />
                <line x1="15" y1="9" x2="9" y2="15" />
                <line x1="9" y1="9" x2="15" y2="15" />
              </svg>
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit}>
            <div className="mb-4">
              <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-1.5">
                邮箱
              </label>
              <input
                id="email"
                type="email"
                autoComplete="email"
                autoFocus
                required
                disabled={loading}
                value={form.email}
                onChange={(e) => setForm({ ...form, email: e.target.value })}
                placeholder="请输入注册邮箱"
                className={inputCls}
              />
            </div>

            <div className="mb-4">
              <label htmlFor="code" className="block text-sm font-medium text-gray-700 mb-1.5">
                验证码
              </label>
              <div className="flex gap-2">
                <input
                  id="code"
                  type="text"
                  required
                  disabled={loading}
                  maxLength={6}
                  value={form.code}
                  onChange={(e) =>
                    setForm({ ...form, code: e.target.value.replace(/\D/g, '') })
                  }
                  placeholder="6 位数字"
                  className={inputCls + ' flex-1'}
                />
                <button
                  type="button"
                  onClick={handleSendCode}
                  disabled={loading || countdown > 0}
                  className="shrink-0 px-4 py-2.5 text-sm font-medium text-blue-600 bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100 disabled:opacity-50 disabled:cursor-not-allowed whitespace-nowrap transition"
                >
                  {countdown > 0 ? `${countdown}s` : '发送验证码'}
                </button>
              </div>
            </div>

            <div className="mb-4">
              <label
                htmlFor="newPassword"
                className="block text-sm font-medium text-gray-700 mb-1.5"
              >
                新密码
              </label>
              <div className="relative">
                <input
                  id="newPassword"
                  type={showPwd ? 'text' : 'password'}
                  autoComplete="new-password"
                  required
                  disabled={loading}
                  value={form.newPassword}
                  onChange={(e) => setForm({ ...form, newPassword: e.target.value })}
                  placeholder="6-20 个字符"
                  className={inputCls + ' pr-10'}
                />
                <button
                  type="button"
                  tabIndex={-1}
                  onClick={() => setShowPwd(!showPwd)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
                >
                  {showPwd ? (
                    <svg
                      width="16"
                      height="16"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94" />
                      <path d="M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19" />
                      <line x1="1" y1="1" x2="23" y2="23" />
                    </svg>
                  ) : (
                    <svg
                      width="16"
                      height="16"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" />
                      <circle cx="12" cy="12" r="3" />
                    </svg>
                  )}
                </button>
              </div>
            </div>

            <div className="mb-6">
              <label
                htmlFor="confirmPassword"
                className="block text-sm font-medium text-gray-700 mb-1.5"
              >
                确认密码
              </label>
              <input
                id="confirmPassword"
                type="password"
                autoComplete="new-password"
                required
                disabled={loading}
                value={form.confirmPassword}
                onChange={(e) => setForm({ ...form, confirmPassword: e.target.value })}
                placeholder="请再次输入新密码"
                className={inputCls}
              />
            </div>

            <button
              type="submit"
              disabled={loading || !canSubmit}
              className="w-full rounded-lg px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:opacity-90 focus:outline-none focus:ring-2 focus:ring-blue-500/40 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed transition"
              style={{ background: 'linear-gradient(135deg, #3b82f6, #6366f1)' }}
            >
              {loading ? (
                <span className="inline-flex items-center gap-2">
                  <svg width="16" height="16" viewBox="0 0 24 24" className="animate-spin">
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                      fill="none"
                    />
                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
                    />
                  </svg>
                  重置中...
                </span>
              ) : (
                '重置密码'
              )}
            </button>
          </form>

          <p className="mt-7 text-center text-sm text-gray-500">
            想起密码了？
            <Link to="/login" className="ml-1 font-semibold text-blue-600 hover:text-blue-700">
              返回登录
            </Link>
          </p>
        </div>
      </div>
    </div>
  )
}
